services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-fastapi-boilerplate
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    restart: always

